/*******************************************************************************
*  $Source: run_queries $;
*    $Date: 2016/01/29
*    Study: PCORnet
*
*  Purpose: Run PCORnet Data Characterization Query Package v3.0
* 
*   Inputs: 
*	   1) PCORnet CDM v3.0 SAS data stores (datasets or views) 
*	   2) SAS program:  /infolder/data_characterization_query.sas
*
*  Outputs: 
*          1) SAS dataset for each query stored in /dmlocal
*               (e.g. dem_l3_n.sas7bdat)
*          2) Print of each query in PDF file format stored in /drnoc
*               (<DataMart Id>_<response date>_data_characterization_query.pdf)
*          3) SAS transport file of SAS datasets for each query stored in /drnoc
*               (<DataMart Id>_<response date>_data_characterization.cpt)
*          4) SAS log file of query portion stored in /drnoc
*               (<DataMart Id>_<response date>_data_characterization_query.log)
*
*  Requirements:  
*                1) Program run in SAS 9.3 or higher
*                2) Each site is required to create the following sub-directory 
*                   structure on its network/server. The subdirectories must 
*                   reside within an outer folder which contains the query name 
*                   from the DRN Query Tool (e.g. PROD_P02_DQA_FDPRO_DCQ_T1D3_r001_v01)
*                   a) /dmlocal: folder containing output generated by the 
*                       request that should be saved locally but not returned to
*                       DRN OC. Output may be used locally or to facilitate 
*                       follow-up queries.
*                   b) /drnoc: folder containing output generated by the request 
*                       that should be returned to the DRN OC via the PCORnet DRN
*                       Query Tool (DRN QT). These tables consist of aggregate 
*                       data/output and transfer the minimum required to answer
*                       the analytic question.
*                   c) /sasprograms: folder containing the master SAS program 
*                       that must be edited and then executed locally.
*                       (i.e. RUN_QUERIES.SAS)
*                   d) /infolder: folder containing all input and lookup files 
*                       needed to execute request. Input files are created for 
*                       each request by the DRN OC Data Characterization team; the 
*                       contents of this folder should not be edited.
*                       (i.e. DATA_CHARACTERIZATION_QUERY.SAS)
*
*  Actions needed: 
*               1) User provides libname path where data resides (section below)
*                     (Example: /ct/pcornet/data/)
*               2) User provides root network/server path where the required
*                     sub-directory structure has been created (section below) 
*                     (Example: /ct/pcornet/queries/PROD_P02_DQA_FDPRO_DCQ_T1D3_r001_v01/) 
*                  ###  DO NOT add sub-directory structure (i.e. /dmlocal) ###
*               3) User provides the low cell count value (section below)
*                     (Example: 20) (default is zero)
*******************************************************************************/

********************************************************************************
* Provide user defined values
********************************************************************************;
 /*Enter directory where data is stored:*/             %let dpath=/ct/pcornet_dc/data/;
 /*Enter network/server directory: */                  %let qpath=/ct/pcornet_dc/queries/;
 /*Enter threshold value:*/                            %let threshold=0;
********************************************************************************
* End of user provided values
*******************************************************************************;

********************************************************************************
* Submit data characterization query program
********************************************************************************;
%include "&qpath.infolder/data_characterization_query.sas";
********************************************************************************;
