/*******************************************************************************
*  $Source: run_queries $;
*    $Date: 2017/12/21
*    Study: PCORnet
*
*  Purpose: Run the query portion of PCORnet Data Curation Query Package v3.12
* 
*   Inputs: 
*	    1) PCORnet CDM v3.1 SAS data stores (datasets or views) 
*	    2) SAS programs:  	data_curation_query.sas stored in /infolder
* 						   	pcornet_code_errors.sas stored in /infolder
* 		3) Reference files: dc_reference.cpt stored in /infolder
*
*  Outputs: 
*       From data_curation_query.sas
*           1) SAS dataset for each query stored in /dmlocal
*                (e.g. dem_l3_n.sas7bdat)
*           2) Print of each query in PDF file format stored in /drnoc
*                (<DataMart Id>_<response date>_data_curation_query.pdf)
*           3) SAS transport file of SAS datasets for each query stored in /drnoc
*                (<DataMart Id>_<response date>_data_curation.cpt)
*           4) SAS log file of query portion stored in /drnoc
*                (<DataMart Id>_<response date>_data_curation_query.log)
*           5) SAS dataset of DataMart meta-data stored in /dmlocal
*                (datamart_all.sas7bdat)
* 
*   	From pcornet_code_errors.sas
*    	1) Up to 5 SAS datasets stored in /dmlocal containing all records which violate one or more of the heuristics
*    	for the given code type, and 1 summary dataset of the results:
* 			baddx.sas7bdat
*	    	badpx.sas7bdat
*	    	badrxcui.sas7bdat
*	    	badndc.sas7bdat
*	    	badloinc.sas7bat
*   	    code_error_summary.sas7bdat (# and % of bad records per table)
* 	    2) CSV versions of the 6 datasets stored in /dmlocal
*	 	3) PCORnet_Code_Errors.pdf stored in /drnoc (contains a partial print of key fields from each of the above datasets)
* 		4) SAS log file of pcornet code errors portion stored in /drnoc
*                (<DataMart Id>_<response date>_pcornet_code_errors.log)
*
*
*  Requirements:  
*                1) Program run in SAS 9.3 or higher
*                2) Each site is required to create the following sub-directory 
*                   structure on its network/server. The subdirectories must 
*                   reside within an outer folder which contains the query name 
*                   from the DRN Query Tool (e.g. PROD_P02_DQA_FDPRO_DCQ_T1D3_r001_v01)
*                   a) /dmlocal: folder containing output generated by the 
*                       request that should be saved locally but not returned to
*                       DRN OC. Output may be used locally or to facilitate 
*                       follow-up queries.
*                   b) /drnoc: folder containing output generated by the request 
*                       that should be returned to the DRN OC via the PCORnet DRN
*                       Query Tool (DRN QT). These tables consist of aggregate 
*                       data/output and transfer the minimum required to answer
*                `       the analytic question.
*                   c) /sasprograms: folder containing the master SAS program 
*                       that must be edited and then executed locally.
*                       (i.e. RUN_QUERIES.SAS)
*                   d) /infolder: folder containing all input and lookup files 
*                       needed to execute request. Input files are created for 
*                       each request by the DRN OC Data Curation team; the 
*                       contents of this folder should not be edited.
*                       (i.e. DATA_CURATION_QUERY.SAS)
*
*  Actions needed: 
*               1) User provides libname path where data resides (section below)
*                     (Example: /ct/pcornet/data/)
*               2) User provides root network/server path where the required
*                     sub-directory structure has been created (section below) 
*                     (Example: /ct/pcornet/queries/PROD_P02_DQA_FDPRO_DCQ_T1D3_r001_v01/) 
*                  ###  DO NOT add sub-directory structure (i.e. /dmlocal) ###
*               3) User provides the low cell count value (section below)
*                     (Example: 20) (default is 11)
*******************************************************************************/

********************************************************************************
* Provide user defined values
********************************************************************************;
 /*Enter directory where data is stored:*/             %let dpath=;
 /*Enter network/server directory: */                  %let qpath=;
 /*Enter threshold value:*/                            %let threshold=11;
********************************************************************************
* End of user provided values
*******************************************************************************;

/********************************************************************************
* Submit code errors program
*********************************************************************************/
%include "&qpath.infolder/pcornet_code_errors.sas";

********************************************************************************
* Submit data curation query program
********************************************************************************;
%include "&qpath.infolder/data_curation_query.sas";
********************************************************************************;
