/*******************************************************************************
*  $Source: 01_run_code_errors $;
*    $Date: 2018/09/27
*    Study: PCORnet
*
*  Purpose: Run PCORnet code errors portion of PCORnet Data Curation Query Package v4.12
* 
*   Inputs: 
*	    1) PCORnet CDM v4.1 SAS data stores (datasets or views) 
*	    2) SAS programs: pcornet_code_errors.sas stored in /infolder
* 		3) Reference files: None
*
*  Outputs: 
*           1) SAS dataset for each query output table stored in /dmlocal
*                (e.g. bad_code_summary.sas7bdat)
*           2) Print of each query in PDF file format stored in /drnoc
*                (e.g. <DataMart Id>_<response date>_pcornet_code_errors.pdf)
*           3) SAS log file of query portion stored in /drnoc
*                (e.g.<DataMart Id>_<response date>_pcornet_code_errors.log)

*
*  Requirements:  
*                1) Program run in SAS 9.3 or higher
*                2) Each site is required to create the following sub-directory 
*                   structure on its network/server. The subdirectories must 
*                   reside within an outer folder which contains the query name 
*                   from the DRN Query Tool (e.g. PROD_P02_DQA_FDPRO_DCQ_T1D3_r001_v01)
*                   a) /dmlocal: folder containing output generated by the 
*                       request that should be saved locally but not returned to
*                       DRN OC. Output may be used locally or to facilitate 
*                       follow-up queries.
*                   b) /drnoc: folder containing output generated by the request 
*                       that should be returned to the DRN OC via the PCORnet DRN
*                       Query Tool (DRN QT). These tables consist of aggregate 
*                       data/output and transfer the minimum required to answer
*                       the analytic question.
*                   c) /sasprograms: folder containing the master SAS program 
*                       that must be edited and then executed locally.
*                   d) /infolder: folder containing all input and lookup files 
*                       needed to execute request. Input files are created for 
*                       each request by the DRN OC Data Curation team; the 
*                       contents of this folder should not be edited.
*
*  Actions needed: 
*               1) User provides libname path where data resides (section below)
*                     (Example: /ct/pcornet/data/)
*               2) User provides root network/server path where the required
*                     sub-directory structure has been created (section below) 
*                     (Example: /ct/pcornet/queries/PROD_P02_DQA_FDPRO_DCQ_T1D3_r001_v01/) 
*                  ###  DO NOT add sub-directory structure (i.e. /dmlocal) ###
*               3) User provides the low cell count value (section below)
*                     (Example: 20) (default is 11)
*               4) User provides the lookback years if requested to do so (section below)
*                     (Example: 20) (default is 20)
*******************************************************************************/

********************************************************************************
* Provide user defined values
********************************************************************************;
 /*Enter directory where data is stored:*/             %let dpath= ;
 /*Enter network/server directory: */                  %let qpath= ;

********************************************************************************
* End of user provided values
*******************************************************************************;

********************************************************************************
* Submit pcornet code errors query program 
********************************************************************************;
%include "&qpath.infolder/pcornet_code_errors.sas";
